steps:

  - id: "init"
    dir: infra
    name: "${_IMAGE}"
    entrypoint: "terraform"
    args:
      - "init"
      - "-no-color"
  - id: "workspace"
    dir: infra
    name: "${_IMAGE}"
    entrypoint: "terraform"
    args:
      - "workspace"
      - "select"
      - ${_ENV}
  - id: "validate"
    dir: infra
    name: "${_IMAGE}"
    entrypoint: "terraform"
    args:
      - "validate"
      - "-no-color"
  - id: "plan"
    dir: infra
    name: "${_IMAGE}"
    entrypoint: "terraform"
    args:
      - "plan"
      - "-no-color"
      - "-var-file=${_ENV}.tfvars"
      - "-lock=false"

# logsBucket: 'CLOUD'
substitutions:
  _IMAGE: placeholder
  _ENV: placeholder
options:
  logging: CLOUD_LOGGING_ONLY